language: cpp
compiler: clang

branches:
  only:
    - master 

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev
      - ninja-build

env:
  - CMAKE_BUILD_TYPE=DEBUG
  - CMAKE_BUILD_TYPE=RELEASE

# Build steps
script:
  - export SRC_DIR="`pwd`"
  - $CXX --version
  - cmake --version
  - mkdir "$TRAVIS_BUILD_DIR/build"
  - cd "$TRAVIS_BUILD_DIR/build"
  - cmake -GNinja "$SRC_DIR"
  - ninja -v
